Update build-and-push-to-aws-ecr.yml
Adding update ECS service

diff --git a/.github/workflows/build-and-push-to-aws-ecr.yml b/.github/workflows/build-and-push-to-aws-ecr.yml
--- a/.github/workflows/build-and-push-to-aws-ecr.yml
+++ b/.github/workflows/build-and-push-to-aws-ecr.yml
@@ -1,8 +1,10 @@
-name: Push to ECR
+name: Push to ECR and Update ECS
 
 env:
-  AWS_REGION: us-east-1
+  AWS_REGION: eu-central-1
   ECR_REPOSITORY: game-sys-test-task
+  ECS_CLUSTER: demo-cluster              # Проверь имя кластера в Terraform
+  ECS_SERVICE: game-sys-service           # Проверь имя сервиса в Terraform
 
 on:
   workflow_dispatch:
@@ -23,7 +25,7 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::988182271356:role/ecr-pusher_repo_game-sys-test-task
-          aws-region: eu-central-1
+          aws-region: $AWS_REGION
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
@@ -38,3 +40,20 @@ jobs:
           
           docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           docker push $REGISTRY/$ECR_REPOSITORY:latest
+
+      - name: Update ECS Service
+        run: |
+          echo "Checking if ECS Service exists..."
+          # Пытаемся получить описание сервиса. Если его нет, команда вернет ошибку, которую мы поймаем.
+          SERVICE_STATUS=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query "services[0].status" --output text 2>&1 || true)
+          
+          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
+            echo "Service is ACTIVE. Triggering new deployment..."
+            aws ecs update-service \
+              --cluster ${{ env.ECS_CLUSTER }} \
+              --service ${{ env.ECS_SERVICE }} \
+              --force-new-deployment \
+              --region ${{ env.AWS_REGION }}
+          else
+            echo "Service not found or not active (Status: $SERVICE_STATUS). Skipping update. Terraform will create it on next apply."
+          fi
